
[workspace]
members = ["http","server"]
resolver = "2"

# [workspace.package]
# name = "httpserver"
# version = "0.0.1"
# edition = "2021"
# description = ""
# license = "MIT"
# categories = ["server"]
